extraction:
  cpp:
    prepare:
      packages:
      - autoconf-archive
      - libssl-dev
    after_prepare:
    - cd "$LGTM_WORKSPACE"
    - mkdir installdir
    - wget https://github.com/tpm2-software/tpm2-tss/releases/download/2.3.1/tpm2-tss-2.3.1.tar.gz
    - echo '7096576c1946b85ec9c92b39e0ed3409ec01bdb97d7863ead033243d5433dee7  tpm2-tss-2.3.1.tar.gz' | sha256sum --check
    - tar xf tpm2-tss-2.3.1.tar.gz
    - cd tpm2-tss-2.3.1
    - ./configure --prefix="$LGTM_WORKSPACE/installdir/usr" --disable-doxygen-doc
    - make install
    - export PKG_CONFIG_PATH="$LGTM_WORKSPACE/installdir/usr/lib/pkgconfig:$PKG_CONFIG_PATH"
    - export LD_LIBRARY_PATH="$LGTM_WORKSPACE/installdir/usr/lib:$LD_LIBRARY_PATH"
