sudo: required
language: c
services:
  - docker

compiler:
  - gcc
  - clang

matrix:
  include:
    - compiler: gcc
      env: ENABLE_COVERAGE=true
    - compiler: clang
      env: ENABLE_COVERAGE=false

script:
  - ./.ci/travis.run

after_failure:
  - cat build/test-suite.log
